export const light = {
  primaryBackground: '#FFFFFF',
  secondaryBackground: '#FF630A',
  primaryText2: '#000',
  secondaryText: '#FFFFFF',
  tertiaryText: '#FF630A',
  buttonBackground: '#FF811A', // Grediant color- FF5F06 -> FF8D38(LinearGrad-71 degree) ,
  buttonText: '#FFFFFF',
  primaryText: '#202224',
  inputbg: '#F1F4F9',
  inputtextcolor: '#A6A6A6',
  signinbtnbackground: '#FF7300',
  checkboxbg: '#A3A3A3',
  checkboxborder: '#000000',
  sidebarborder: '#3F3F44',
  iconhovercolor: '#CACACA',
  btnactivecolor: '#00B69B',
  btninactivecolor: '#FCBE2D',
  btnrejectedcolor: '#FD5454',
  deletetextcolor: '#E40000',
  graphtextgreen: '#2F8506',
  barcolor1: '#CCEABB',
  barcolor2: '#FDCB9E',
  bookingscardcolor: '#3A3A3A',
  bookingstextwhitecolor: '#FEFEFE',
  dashboardbookingcard: '#F6F6F6',
  bordercolor: '#979797',
  uploadbtncolor: '#DEDEDE'
}
