
// import StoreProvider from "./storeProvider";
// import Navbar from "@/components/User/Navbar/Navbar";
// import SessionProviderWrapper from "@/components/SessionProviderWrapper";
// import { SessionProvider } from "next-auth/react";
// import SessionProviderWrapper from "@/components/SessionProviderWrapper";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "@/components/LayoutWrapper";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Safar Wanderlust- Group Travel Company",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
    
  );
}
// export default function RootLayout({ children }) {
//   return (
//     // <html lang="en">
//     //   <body
//     //     className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//     //   >
//     //     <LayoutWrapper>{children}</LayoutWrapper>
//     //   </body>
//     // </html>
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <SessionProviderWrapper> 
//           <LayoutWrapper>{children}</LayoutWrapper>
//         </SessionProviderWrapper>
//       </body>
//     </html>
//   );
// }
