name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Copy files to VPS using sshpass and scp
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}      # e.g., 88.222.241.171
          VPS_USER: ${{ secrets.VPS_USER }}      # e.g., root
          VPS_PASS: ${{ secrets.VPS_PASS }}      # your password
          DEST_PATH: ${{ secrets.DEST_PATH }}    # e.g., /frontend
        run: |
          sshpass -p "$VPS_PASS" scp -o StrictHostKeyChecking=no -r ./ $VPS_USER@$VPS_HOST:$DEST_PATH
